# 2.1 reset button
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateSliderInput(session = session, inputId = "sliderInput_2_1_2_1", min = 0, max = 1, value = 0.5, step = 0.01)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateRadioButtons(session = session, inputId = "radioButtons_2_1_2_2", choices = list("Yes" = TRUE, "No" = FALSE), selected = TRUE)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateNumericInput(session = session, inputId = "numericInput_2_1_2_3", value = 42)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateSelectInput(session, inputId = "selectInput_2_1_2_4", choices = factor_variables_2_1(), selected = factor_variables_2_1()[[1]])})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateSelectInput(session, inputId = "selectInput_2_1_2_5", choices = factor_variables_2_1(), selected = factor_variables_2_1()[[2]])})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_1_1", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_1_2", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_1_3", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_1_4", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_1_5", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateNumericInput(session = session, inputId = "numericInput_2_1_3_2_1", value = 12)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateNumericInput(session = session, inputId = "numericInput_2_1_3_2_2", value = 10)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateNumericInput(session = session, inputId = "numericInput_2_1_3_2_3", value = 4)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateSelectInput(session = session, inputId = "selectInput_2_1_2_2_4", choices = select_box_input(vector = c(5, 10, 25, 50, 100)), selected = 10)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateRadioButtons(session = session, inputId = "radioButtons_2_1_3_3_1", choices = list("Yes" = TRUE, "No" = FALSE), selected = TRUE)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateRadioButtons(session = session, inputId = "radioButtons_2_1_3_3_2", choices = select_box_input(vector = c("left", "top", "right", "bottom")), selected = "bottom")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateRadioButtons(session = session, inputId = "radioButtons_2_1_3_3_3", choices = select_box_input(vector = c("horizontal", "vertical")), selected = "horizontal")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateRadioButtons(session = session, inputId = "radioButtons_2_1_3_3_4", choices = list("Yes" = TRUE, "No" = FALSE), selected = FALSE)})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_1", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_2", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_3", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_4", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_5", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_6", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_7", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_8", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_9", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_10", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_11", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_12", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_13", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_14", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_15", value = "")})
shiny::observeEvent(eventExpr = input$actionButton_2_1, handlerExpr = {shiny::updateTextInput(session = session, inputId = "textInput_2_1_3_4_16", value = "")})